name: SPFx CI CD

on:
  push:
    branches:
      - dev
      - githubactionsgeneral

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      packagePath: sharepoint/solution/test-list-items.sppkg
    
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 10.x

    - name: Install dependencies
      run: npm ci
    
    - name: Build solution
      run: gulp build
      
    - name: Test solution
      run: npm test
              
    - name: Bundle and package
      run: |
        gulp bundle --ship
        gulp package-solution --ship

    - name: Upload Build Package
      uses: actions/upload-artifact@v2
      with:
        name: packageFile
        path: ${{ env.packagePath }}

  deployUAT:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/githubactionsgeneral'
    env:
      siteUrl: https://in8aakbh.sharepoint.com/sites/AppIndex

    steps:

    - name: Download pacakge (sppkg file)
      uses: actions/download-artifact@v1
      with:
        name: packageFile
        
    - name: Office 365 CLI Login
      uses: pnp/action-cli-login@v1.0.0
      with:
        ADMIN_USERNAME: ${{ secrets.adminUsername }}
        ADMIN_PASSWORD: ${{ secrets.adminPassword }}
        
      # Run script bash
    - name: Office 365 CLI Runscript bash
      uses: pnp/action-cli-runscript@v1.0.0
      env:
        packagePath: packageFile/test-list-items.sppkg
      with:
        O365_CLI_SCRIPT_PATH: './scripts/DeployPackage.sh'
        
  deployPROD:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    env:
      siteUrl: https://in8aakbh.sharepoint.com/sites/UHSD2
      packagePath: sharepoint/solution/test-list-items.sppkg

    steps:

    - name: Office 365 CLI Login
      uses: pnp/action-cli-login@v1.0.0
      with:
        ADMIN_USERNAME: ${{ secrets.adminUsername }}
        ADMIN_PASSWORD: ${{ secrets.adminPassword }}
        
      # Run script bash
    - name: Office 365 CLI Runscript bash
      uses: pnp/action-cli-runscript@v1.0.0
      with:
        O365_CLI_SCRIPT_PATH: './scripts/DeployPackage.sh'
