name: SPFx CI CD

on:
  push:
    branches:
      - dev
      - githubactions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 10.x

    - name: Install dependencies
      run: npm ci
    
    - name: Build solution
      run: gulp build
      
    - name: Test solution
      run: npm test
      
    - name: Bundle and package
      run: |
        gulp bundle --ship
        gulp package-solution --ship
